#' Returns a character vector for the code chunk to retrieve the figure data
#' frame using `Datenreport2022::get_figure_df`
#'
#' @param chunk_label Character
#' @param function_call Character
#' @param function_params Character
#' @
#' @return Character vector
#' @export
#'
#' @examples
#' writeLines(tpl_get_figure_df(chunk_label = 1L, function_params = "df, figure_count = 1L))
tpl_get_figure_df <- function(
  chunk_label,
  function_call = "Datenreport2022::get_figure_df",
  function_params
) {
  template <- c(
    glue::glue(
      "\n```{r prep-fig-<<chunk_label>>, include = FALSE}",
      .open = "<<",
      .close = ">>"
    ),
    glue::glue(
      "df_fig <-<<function_call>>(<<function_params>>)",
      .open = "<<",
      .close = ">>"
    ),
    "```"
  )

  return(template)
}

#' Returns a character vector for the code chunk to insert a heading
#'
#' @return Character vector
#' @export
#'
#' @examples
#' writeLines(tpl_heading())
tpl_heading <- function() {
  template <- c(
    "\n```{r heading-fig-{{label}}, results= 'asis', eval = df_fig$is_heading[[1]]}",
    "cat(paste(\"#\", df_fig$heading[[1]]))",
    "```"
  )

  return(template)
}

#' Returns a character vector for the code chunk to insert a subheading
#'
#' @return Character vector
#' @export
#'
#' @examples
#' writeLines(tpl_subheading())
tpl_subheading <- function() {
  template <- c(
    "\n```{r subheading-fig-{{label}}, results= 'asis', eval = df_fig$is_subheading[[1]]}",
    "cat(paste(\"##\", df_fig$subheading[[1]]))",
    "```"
  )

  return(template)
}

#' Returns a character vector for the code chunk to plot a figure using
#' `RUBer::plot_figure`
#'
#' @param tab_placeholder Character, pandoc does not support the insertion of
#'                        tabs, which is why a placeholder text is needed that
#'                        will get replaced with tabs in post-processing,
#'                        defaults to "PLACEHOLDER_TAB"
#' @param warning Boolean, whether to suppress the warnings generated by this
#'                code chunk, defaults to TRUE.
#'
#' @return Character vector
#' @export
#'
#' @examples
#' writeLines(tpl_plot_figure())
tpl_plot_figure <- function(
  tab_placeholder = "PLACEHOLDER_TAB",
  suppress_warnings = TRUE
) {
  template <- c(
    glue::glue(
      "\n```{r fig{{label}}, fig.cap = paste0('<<tab_placeholder>>',df_fig$figure_caption[[1]]), fig.height=df_fig$figure_height[[1]], warning = <<suppress_warnings>>}",
      .open = "<<",
      .close = ">>"
    ),
    "RUBer::plot_figure(df_fig)",
    "```"
  )

  return(template)
}
